### ISSUE TITLE
IntelliJ could not find or load main class

### ISSUE THREAD

**Issue by ivyyangyq** [nus-cs2103-AY1819S2/forum#11]
After I clone the addressbook-level1 on my computer and built the project in IntelliJ, when I tried to run AddressBook, the following error appeared.

Error: Could not find or load main class seedu.addressbook.AddressBook
Caused by: java.lang.ClassNotFoundException: seedu.addressbook.AddressBook

I've tried most methods listed in https://stackoverflow.com/questions/10654120/error-could-not-find-or-load-main-class-in-intellij-ide such as editing configuration, rebuilding project, check project compiler output path, reinstalling IntelliJ, recloning project and even reinstalling java 9. So far nothing works. Could someone help me with this issue?

**Comment by daDangminh** [comment]
This is probably due to choosing the wrong project folder if I am not mistaken. I faced this problem a few days ago. What I did was recreating a new project whose project location is the addressbook-level1 folder. (Before recreating the project, you must go to your local project directory and remove the IntelliJ files and folder ending with .idea and .iml, so that IntelliJ no longer recognizes it as an IntelliJ project)

Then all you need to do next is navigating to AddressBook.java file, right click and choose run AddressBook.main(). Do let me know if it resolves the issue. :)

**Comment by ivyyangyq** [comment]
Unfortunately this does not work for me. The project path is correct on my computer. I've also tried reimporting the project or creating the project from a new folder. It still does not resolve the issue.

> This is probably due to choosing the wrong project folder if I am not mistaken. I faced this problem a few days ago. What I did was recreating a new project whose project location is the addressbook-level1 folder. (Before recreating the project, you must go to your local project directory and remove the IntelliJ files and folder ending with .idea and .iml, so that IntelliJ no longer recognizes it as an IntelliJ project)
> 
> Then all you need to do next is navigating to AddressBook.java file, right click and choose run AddressBook.main(). Do let me know if it resolves the issue. :)

**Comment by gohyinhao** [comment]
The problem could be that you need to set your classpath correctly. When you try to load up the program, the JVM tries to load the class definition but the class was not found in the classpath, hence throwing the exception. You can read up more about it at https://stackoverflow.com/questions/34413/why-am-i-getting-a-noclassdeffounderror-in-java

To add a directory to classpath in IntelliJ (extracted this snippet from https://stackoverflow.com/questions/854264/how-to-add-directory-to-classpath-in-an-application-run-profile-in-intellij-idea)
1. click on the Project view or unhide it by clicking on the "1: Project" button on the left border of the window or by pressing Alt + 1
2. find your project or sub-module and click on it to highlight it, then press F4, or right click and choose "Open Module Settings"
3. click on the dependencies tab
4. Click the "+" button on the right and select "Jars or directories..."
5. Find your path and click OK
6. In the dialog with "Choose Categories of Selected File", choose Classes (even if it's properties), press OK and OK again
7. You can now run your application and it will have the selected path in the class path

Alternatively, if you want to run the program through command line, assuming you made no changes after cloning it, go to wherever you stored addressbook-level1 in, i.e. "..\addressbook-level1\src\" then run the command "java seedu.addressbook.AddressBook".

Hope this helps

**Comment by ccristina** [comment]
@ivyyangyq Let us know if you still have problems. You may contact your TA or our main TA Yuan Chuan to meet them and fix the problems.

**Comment by ivyyangyq** [comment]
Thanks but this also does not work. I have problem running addressbook in terminal as well. But java does not have any problem with other files.
> The problem could be that you need to set your classpath correctly. When you try to load up the program, the JVM tries to load the class definition but the class was not found in the classpath, hence throwing the exception. You can read up more about it at https://stackoverflow.com/questions/34413/why-am-i-getting-a-noclassdeffounderror-in-java
> 
> To add a directory to classpath in IntelliJ (extracted this snippet from https://stackoverflow.com/questions/854264/how-to-add-directory-to-classpath-in-an-application-run-profile-in-intellij-idea)
> 
> 1. click on the Project view or unhide it by clicking on the "1: Project" button on the left border of the window or by pressing Alt + 1
> 2. find your project or sub-module and click on it to highlight it, then press F4, or right click and choose "Open Module Settings"
> 3. click on the dependencies tab
> 4. Click the "+" button on the right and select "Jars or directories..."
> 5. Find your path and click OK
> 6. In the dialog with "Choose Categories of Selected File", choose Classes (even if it's properties), press OK and OK again
> 7. You can now run your application and it will have the selected path in the class path
> 
> Alternatively, if you want to run the program through command line, assuming you made no changes after cloning it, go to wherever you stored addressbook-level1 in, i.e. "..\addressbook-level1\src" then run the command "java seedu.addressbook.AddressBook".
> 
> Hope this helps

**Comment by ivyyangyq** [comment]
![screen shot 2019-02-01 at 16 36 04](https://user-images.githubusercontent.com/39294608/52112341-28c15780-2641-11e9-8a35-2e4ac73dc94d.png)
![screen shot 2019-02-01 at 16 42 56](https://user-images.githubusercontent.com/39294608/52112344-29f28480-2641-11e9-8ea3-fc945a279d78.png)
Here is the error message after I tried to run the program. The classpath displayed on the screen is the correct actual path of my output class file.

**Comment by JonathanLeeWH** [comment]
@ivyyangyq can you take a screenshot of the project panel the one on the left side of IntelliJ where we can take a look at your directory structure. If possible expand your src directory and also out directory. I am not sure about the error not sure if that screenshot might help the rest in finding a solution.

Sorry may I also ask how did you create the project with IntelliJ for example the process.

I understand you clone the repository to your own computer in some directory.

Not sure if this is the process you follow but you can try cloning the repository to a directory then open intelliJ click on File > import project > choose the project directory which you clone the repository to > follow the steps there should not be anything you need to change just keep clicking next and then finish. You can try running again and see if it works.

**Comment by kylase-learning** [comment]
Your `src` folder needs to be blue. That means IntelliJ knows that it is folder containing the Source files.

You can go to Project Structure > Modules and mark `src` as Sources.

**Comment by ivyyangyq** [comment]
![screen shot 2019-02-01 at 22 52 31](https://user-images.githubusercontent.com/39294608/52130086-36440500-2674-11e9-9d6f-2c0fa876b2fb.png)
@kylase-learning I think this looks correct.
@JonathanLeeWH The process you described was exactly the one I followed. I've tried it a few times and it still does not work.
Interestingly, when I cloned addressbooklevel2 it also did not work.

**Comment by JonathanLeeWH** [comment]
@ivyyangyq It looks alright as it did show the run (green arrow) which means technically there is a main class or can be run (not sure if you want to try and go to AddressBook.java and click the green arrow besides the main() method line) but for some reason if you still see that error may be has something to do with the configuration (just a guess).

This might be an unpopular opinion but since you tried everything like recloning, cloning a different repository and changing settings etc.

May I suggest that I am not sure if it will work for you but it is worth a try and based on your screenshot you seem to be either using some linux distribution or macOS so if can try resetting your entire IntelliJ IDE settings to default if you want and see if it works. You can do so without reinstalling by deleting the configuration folder which can be found in this page (https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs) for Windows, Linux or MacOS respectively. If you still want to keep your old settings you can try exporting it first by going File and export settings which will export as a zip store it somewhere else instead of the default directory.

**Alternatively: You can try backup the configuration folder which I meant as eg. ".IdeaIC2018.3" the entire folder instead of just the config folder and then delete the entire ".IdeaIC2018.3" (the version number may vary depending on what version you installed but it should be along the lines of .Ideal followed by whether you download community edition or the complete edition then the version number)"**

After deleting the configuration for IntelliJ IDE, try relaunching IntelliJ IDE, it should show something like want to import existing configuration or do not import existing configuration. Choose do not import existing configuration to start from default settings and see maybe if it works for you.

You can always import your old settings back if it still does not work for you by going File > import settings and select the settings zip file you back up earlier.

**Comment by ivyyangyq** [comment]
@JonathanLeeWH I tried deleting the IntelliJ setting and using the default. Still no luck :(

**Comment by JonathanLeeWH** [comment]
@ivyyangyq I see. I apologise I am unable to provide much help. Maybe you can approach a tutor or professor to have a look at your computer as Dr @ccristina suggested.

**Comment by ivyyangyq** [comment]
Okay the problem is the blank space in the path. Thanks guys for helping me!

**Comment by mohammadsaidi101** [comment]
> Okay the problem is the blank space in the path. Thanks guys for helping me!

how did you solved it ?

**Comment by ArasOG** [comment]
@mohammadsaidi101 empty spaces in the classpath was the problem. I had the same issue. You have to make sure the path has no blank spaces otherwise intellij wont find it.

**Comment by lsrom** [comment]
I just came here to say that its 2024 and Intellij 2024.4 still has this issue. And it freaking installs itself like that.
