### ISSUE TITLE
Regarding the iterative development process of CS2103

### ISSUE THREAD

**Issue by fterh** [nus-cs2103-AY1819S2/forum#52]
Hi teaching team! I have a question. In Project Assessment (https://nus-cs2103-ay1819s2.github.io/cs2103-website/admin/project-assessment.html), it's stated that only the largest feature is evaluated for feature quality. Also, it's been mentioned in the lectures that there should be an iterative process, which is what CS2103 is aiming for. 

My question is: if I have a feature planned (that satisfies all the other requirements, like user testable, front-end, sufficient complexity, etc.), should I be deliberately "dumbing it down" (e.g. implement it in an inefficient manner or something) for v1.2 just so I can apply the iterative developmental process for v1.3 and v1.4?

Because if I were to implement it fully in a single PR for v1.2 for instance, I'd be writing code for new features for v1.3 and v1.4, but ultimately, only the largest feature will be evaluated anyway, which is counter-productive in a sense. So I'm not entirely sure how I should approach this, thanks! :)

**Comment by okkhoy** [comment]
@fterh We will be evaluating the _depth of the feature_ that includes design considerations, developer documentation etc.,  for the largest feature. This would be the one you will include and state explicitly in the portfolio page. 

For all other things (like testability, testing, code quality etc.,) we will consider everything that you have done.
If you have planned for more than one feature, then you can do one feature per milestone (though the module itself doesn't require you to do more than one feature 🙂). If your feature is big, it would naturally be better to plan it so that you have something to do for every milestone; this, in turn, helps manage the workload as well!

It is more important to ensure the product is in a working state during each milestone.

**Comment by fterh** [comment]
Thanks!
